### ISSUE TITLE
turf.random 随机生成点报错

### ISSUE THREAD

**Issue by LeeYunDu** [Psilocine/turfjs-docs-Zh-CN#15]
在typescript环境下 
const points = turf.random('points', 100, {
    bbox: [-70, 40, -60, 60]
  })
vue-router.esm-bundler.js:3295 ReferenceError: i is not defined 
 at Function.module.exports.point

for 循环中 没有定义 i

**Comment by Psilocine** [comment]
@LeeYunDu 你好！据我所知 turf 没有 random 方法。
这里是翻译文档，如果 api 有问题，欢迎去 turf 官方提 pr fix～
